export const GAME_CONFIG = {
  // 世界
  WORLD_SIZE: 256,
  CHUNK_SIZE: 16,
  CHUNK_HEIGHT: 256,
  CHUNK_SECTION_HEIGHT: 16,
  SEA_LEVEL: 64,

  // 出生点
  SPAWN_X: 50,
  SPAWN_Z: 50,
  SPAWN_Y_OFFSET: 30, // 出生点距离地面的高度

  // 渲染
  DEFAULT_RENDER_DISTANCE: 6,
  MIN_RENDER_DISTANCE: 4,
  MAX_RENDER_DISTANCE: 12,
  FOV: 75,
  FAR_PLANE: 500,
  NEAR_PLANE: 0.1,

  // 玩家
  PLAYER_HEIGHT: 1.8,
  PLAYER_WIDTH: 0.6,
  EYE_HEIGHT: 1.62,
  WALK_SPEED: 4.3,
  SPRINT_SPEED: 5.6,
  JUMP_FORCE: 8,
  GRAVITY: 20,

  // 交互
  REACH_DISTANCE: 10,
  DIGGING_SPEED: 1.0,
  CLICK_THROTTLE: 100,
  AUTO_SAVE_INTERVAL: 30000,

  // 性能
  MAX_CHUNK_LOADS_PER_FRAME: 2,
  MAX_CHUNK_UNLOADS_PER_FRAME: 4,
  MAX_MESH_UPDATES_PER_FRAME: 10,
} as const

export type GameConfig = typeof GAME_CONFIG
