export const CONTROLS = {
  FORWARD: 'KeyW',
  BACKWARD: 'KeyS',
  LEFT: 'KeyA',
  RIGHT: 'KeyD',
  JUMP: 'Space',
  SPRINT: 'ShiftLeft',
  SLOT_1: 'Digit1',
  SLOT_2: 'Digit2',
  SLOT_3: 'Digit3',
  SLOT_4: 'Digit4',
  SLOT_5: 'Digit5',
  SLOT_6: 'Digit6',
  SLOT_7: 'Digit7',
  SLOT_8: 'Digit8',
  SLOT_9: 'Digit9',
  CYCLE_SLOT_NEXT: 'KeyQ',
  CYCLE_SLOT_PREV: 'KeyTab',
  TOGGLE_WHEEL: 'Tab',
  TOGGLE_DEBUG: 'F3',
  PAUSE: 'Escape',
  DIG: 'MouseLeft',
  PLACE: 'MouseRight',
} as const
